Repository HongzCloud/airbnb, pull requests merged in 2021-05, with the labels that each got.

#6 Header 구현
  FE/package-lock.json
  FE/package.json
  FE/public/favicon.ico
  FE/public/index.html
  FE/public/logo192.png
  FE/public/logo512.png
  FE/public/manifest.json
  FE/src/App.css
  FE/src/App.js
  FE/src/components/GlobalStyle.jsx
  FE/src/components/Header/Header.jsx
  FE/src/components/Header/Logo.jsx
  FE/src/components/Header/Menu.jsx
  FE/src/components/Header/MyPage.jsx
  FE/src/components/Main.jsx
  FE/src/index.css
  FE/src/logo.svg
Labels: FE

#8 Footer 구현
  FE/src/components/Footer/AnyWhere.jsx
  FE/src/components/Footer/Floor.jsx
  FE/src/components/Footer/Footer.jsx
  FE/src/components/Footer/NearTravel.jsx
  FE/src/components/Header/MyPage.jsx
  FE/src/components/Main.jsx
Labels: FE

#11 SearchBar 기능 제외 디자인 구현
  FE/src/components/Main.jsx
  FE/src/components/SearchBar/CloseButton.jsx
  FE/src/components/SearchBar/Period.jsx
  FE/src/components/SearchBar/Personnel.jsx
  FE/src/components/SearchBar/Price.jsx
  FE/src/components/SearchBar/SearchBar.jsx
  FE/src/components/SearchBar/SearchButton.jsx
Labels: FE

#12 Spring boot 프로젝트 생성
  .gitignore
  BE/build.gradle
  BE/gradle/wrapper/gradle-wrapper.jar
  BE/gradle/wrapper/gradle-wrapper.properties
  BE/gradlew
  BE/gradlew.bat
  BE/settings.gradle
  BE/src/main/java/com/enolj/airbnb/AirbnbApplication.java
  BE/src/main/resources/application.properties
  BE/src/test/java/com/enolj/airbnb/AirbnbApplicationTests.java
Labels: BE

#26 airbnb mockup API 생성
  BE/src/main/java/com/enolj/airbnb/service/HouseService.java
  BE/src/main/java/com/enolj/airbnb/web/HouseController.java
  BE/src/main/java/com/enolj/airbnb/web/ReservationInfoResponseDTO.java
  BE/src/main/java/com/enolj/airbnb/web/dto/Charge.java
  BE/src/main/java/com/enolj/airbnb/web/dto/CheckDate.java
  BE/src/main/java/com/enolj/airbnb/web/dto/Description.java
  BE/src/main/java/com/enolj/airbnb/web/dto/Fee.java
  BE/src/main/java/com/enolj/airbnb/web/dto/Location.java
  BE/src/main/java/com/enolj/airbnb/web/dto/People.java
  BE/src/main/java/com/enolj/airbnb/web/dto/ReservationDetailDTO.java
  BE/src/main/java/com/enolj/airbnb/web/dto/ReservationRequestDTO.java
  BE/src/main/java/com/enolj/airbnb/web/dto/ReservationResponseDTO.java
  BE/src/main/java/com/enolj/airbnb/web/dto/SearchChargesRequestDTO.java
  BE/src/main/java/com/enolj/airbnb/web/dto/SearchRequestDTO.java
  BE/src/main/java/com/enolj/airbnb/web/dto/SearchResponseDTO.java
  BE/src/main/java/com/enolj/airbnb/web/dto/WishesResponseDTO.java
Labels: BE, feature

#28 CalendarModal 구현
  FE/src/components/SearchBar/CloseButton.jsx
  FE/src/components/SearchBar/Period.jsx
  FE/src/components/SearchBar/Period/Calendar/Calendar.jsx
  FE/src/components/SearchBar/Period/Calendar/Day.jsx
  FE/src/components/SearchBar/Period/CalendarModal.jsx
  FE/src/components/SearchBar/Period/Period.jsx
  FE/src/components/SearchBar/Personnel/Personnel.jsx
  FE/src/components/SearchBar/Price/Price.jsx
  FE/src/components/SearchBar/SearchBar.jsx
  FE/src/components/SearchBar/SearchButton.jsx
Labels: FE

#37 Config 설정
  .gitignore
  BE/src/main/java/com/enolj/airbnb/config/RequestLoggingFilterConfig.java
  BE/src/main/java/com/enolj/airbnb/config/WebConfig.java
  BE/src/main/java/com/enolj/airbnb/service/HouseService.java
  BE/src/main/java/com/enolj/airbnb/web/dto/ReservationInfoResponseDTO.java
  BE/src/test/java/com/enolj/airbnb/AirbnbApplicationTests.java
Labels: BE

#40 mockup API 리팩토링
  BE/src/main/java/com/enolj/airbnb/service/HouseService.java
  BE/src/main/java/com/enolj/airbnb/web/HouseController.java
  BE/src/main/java/com/enolj/airbnb/web/dto/SearchChargesRequestDTO.java
  BE/src/main/java/com/enolj/airbnb/web/dto/SearchRequestDTO.java
  BE/src/main/resources/application.properties
Labels: BE

#45 로그인/로그아웃 API 생성
  .gitignore
  BE/build.gradle
  BE/src/main/java/com/enolj/airbnb/authorization/GitHubOAuth.java
  BE/src/main/java/com/enolj/airbnb/authorization/OAuth.java
  BE/src/main/java/com/enolj/airbnb/domain/user/User.java
  BE/src/main/java/com/enolj/airbnb/domain/user/UserRepository.java
  BE/src/main/java/com/enolj/airbnb/errorHandler/RestTemplateResponseErrorHandler.java
  BE/src/main/java/com/enolj/airbnb/exception/EntityNotFoundException.java
  BE/src/main/java/com/enolj/airbnb/exception/ErrorMessage.java
  BE/src/main/java/com/enolj/airbnb/exception/GitHubTypeException.java
  BE/src/main/java/com/enolj/airbnb/exception/OAuthException.java
  BE/src/main/java/com/enolj/airbnb/exception/TokenException.java
  BE/src/main/java/com/enolj/airbnb/service/UserService.java
  BE/src/main/java/com/enolj/airbnb/web/UserController.java
  BE/src/main/java/com/enolj/airbnb/web/dto/EmailDTO.java
  BE/src/main/java/com/enolj/airbnb/web/dto/TokenDTO.java
  BE/src/main/java/com/enolj/airbnb/web/dto/UserInfoDTO.java
  BE/src/main/java/com/enolj/airbnb/web/dto/UserResponseDTO.java
  BE/src/main/java/com/enolj/airbnb/web/utils/GitHubType.java
  BE/src/main/java/com/enolj/airbnb/web/utils/GitHubUrl.java
  BE/src/main/java/com/enolj/airbnb/web/utils/JwtUtil.java
  BE/src/main/resources/schema.sql
Labels: BE

#46 SearchBar 리팩토링
  FE/src/components/Footer/AnyWhere.jsx
  FE/src/components/Footer/Floor.jsx
  FE/src/components/Footer/NearTravel.jsx
  FE/src/components/SearchBar/Period/Calendar/Calendar.jsx
  FE/src/components/SearchBar/Period/Calendar/Day.jsx
  FE/src/components/SearchBar/Period/CalendarModal.jsx
  FE/src/components/SearchBar/Period/Period.jsx
  FE/src/components/SearchBar/Personnel/Personnel.jsx
  FE/src/components/SearchBar/Price/Price.jsx
  FE/src/components/SearchBar/Price/PriceModal.jsx
  FE/src/components/SearchBar/Price/Slider.jsx
  FE/src/components/SearchBar/SearchBar.jsx
  FE/src/json/data.json
  FE/src/util/addComma.js
  FE/src/util/delay.js
Labels: FE

#48 airbnb 프로젝트 schema 생성
  BE/src/main/resources/schema.sql
Labels: BE

#50 Feat: 프로젝트에 사용할 기본 데이터 삽입
  BE/src/main/resources/data.sql
Labels: BE

#52 mockup API 수정
  BE/src/main/java/com/enolj/airbnb/service/HouseService.java
  BE/src/main/java/com/enolj/airbnb/web/dto/ReservationInfoResponseDTO.java
  BE/src/main/java/com/enolj/airbnb/web/dto/ReservationRequestDTO.java
Labels: BE

#54 MyPage & Oauth
  FE/src/components/Header/MyPage.jsx
Labels: FE

#56 Result Header 구현
  FE/src/App.js
  FE/src/components/Footer/Floor.jsx
  FE/src/components/Footer/Footer.jsx
  FE/src/components/Header/Header.jsx
  FE/src/components/Header/Logo.jsx
  FE/src/components/Header/Menu.jsx
  FE/src/components/Header/MyPage.jsx
  FE/src/components/Header/SearchBar/CloseButton.jsx
  FE/src/components/Header/SearchBar/Period/Calendar/Calendar.jsx
  FE/src/components/Header/SearchBar/Period/Calendar/Day.jsx
  FE/src/components/Header/SearchBar/Period/CalendarModal.jsx
  FE/src/components/Header/SearchBar/Period/Period.jsx
  FE/src/components/Header/SearchBar/Personnel/Personnel.jsx
  FE/src/components/Header/SearchBar/Personnel/PersonnelModal.jsx
  FE/src/components/Header/SearchBar/Price/Price.jsx
  FE/src/components/Header/SearchBar/Price/PriceModal.jsx
  FE/src/components/Header/SearchBar/Price/Slider.jsx
  FE/src/components/Header/SearchBar/SearchBar.jsx
  FE/src/components/Header/SearchBar/SearchButton.jsx
  FE/src/components/Main/AnyWhere.jsx
  FE/src/components/Main/Main.jsx
  FE/src/components/Main/NearTravel.jsx
  FE/src/components/Result/Result.jsx
  FE/src/components/Root.jsx
  FE/src/components/SearchBar/SearchBar.jsx
  FE/src/config/GlobalStyle.jsx
  FE/src/config/MainContextProvider.jsx
  FE/src/config/SearchBarContextProvider.jsx
  FE/src/json/data.json
Labels: FE

#69 airbnb API 구현
  BE/src/main/java/com/enolj/airbnb/domain/house/House.java
  BE/src/main/java/com/enolj/airbnb/domain/house/HouseDAO.java
  BE/src/main/java/com/enolj/airbnb/domain/image/Image.java
  BE/src/main/java/com/enolj/airbnb/domain/image/ImageDAO.java
  BE/src/main/java/com/enolj/airbnb/domain/join/Join.java
  BE/src/main/java/com/enolj/airbnb/domain/join/JoinDAO.java
  BE/src/main/java/com/enolj/airbnb/domain/user/User.java
  BE/src/main/java/com/enolj/airbnb/domain/wish/Wish.java
  BE/src/main/java/com/enolj/airbnb/domain/wish/WishDAO.java
  BE/src/main/java/com/enolj/airbnb/service/HouseService.java
  BE/src/main/java/com/enolj/airbnb/service/UserService.java
  BE/src/main/java/com/enolj/airbnb/web/HouseController.java
  BE/src/main/java/com/enolj/airbnb/web/dto/CheckDate.java
  BE/src/main/java/com/enolj/airbnb/web/dto/Description.java
  BE/src/main/java/com/enolj/airbnb/web/dto/Location.java
  BE/src/main/java/com/enolj/airbnb/web/dto/People.java
  BE/src/main/java/com/enolj/airbnb/web/dto/ReservationDetailDTO.java
  BE/src/main/java/com/enolj/airbnb/web/dto/ReservationInfoResponseDTO.java
  BE/src/main/java/com/enolj/airbnb/web/dto/ReservationRequestDTO.java
  BE/src/main/java/com/enolj/airbnb/web/dto/ReservationResponseDTO.java
  BE/src/main/java/com/enolj/airbnb/web/dto/SearchRequestDTO.java
  BE/src/main/java/com/enolj/airbnb/web/dto/SearchResponseDTO.java
  BE/src/main/java/com/enolj/airbnb/web/dto/WishResponseDTO.java
  BE/src/main/java/com/enolj/airbnb/web/utils/JwtUtil.java
Labels: BE

#73 Houses & Modal 구현
  FE/src/App.js
  FE/src/components/Footer/Footer.jsx
  FE/src/components/Header/Header.jsx
  FE/src/components/Header/MyPage.jsx
  FE/src/components/Header/SearchBar/Period/Period.jsx
  FE/src/components/Header/SearchBar/Personnel/Personnel.jsx
  FE/src/components/Header/SearchBar/Price/Price.jsx
  FE/src/components/Header/SearchBar/Price/PriceModal.jsx
  FE/src/components/Header/SearchBar/SearchBar.jsx
  FE/src/components/Header/SearchBar/SearchButton.jsx
  FE/src/components/Result/Houses/House.jsx
  FE/src/components/Result/Houses/Houses.jsx
  FE/src/components/Result/Modal.jsx
  FE/src/components/Result/ModalCost.jsx
  FE/src/components/Result/ModalInfo.jsx
  FE/src/components/Result/Result.jsx
  FE/src/components/Root.jsx
  FE/src/config/MainContextProvider.jsx
  FE/src/config/ResultContextProvider.jsx
  FE/src/config/SearchBarContextProvider.jsx
  FE/src/util/parseDate.js
Labels: FE

#78 Map 구현
  FE/public/index.html
  FE/src/components/Result/Houses/Houses.jsx
  FE/src/components/Result/Map.jsx
  FE/src/components/Result/ModalCost.jsx
  FE/src/components/Result/Result.jsx
  FE/src/config/ResultContextProvider.jsx
Labels: FE

#80 0527 Refactor
  FE/src/App.js
  FE/src/components/Header/MyPage.jsx
  FE/src/components/Header/SearchBar/Period/Calendar/Calendar.jsx
  FE/src/components/Header/SearchBar/Period/CalendarModal.jsx
  FE/src/components/Header/SearchBar/Price/Price.jsx
  FE/src/components/Header/SearchBar/SearchButton.jsx
  FE/src/components/Result/Houses/House.jsx
  FE/src/components/Result/Map.jsx
  FE/src/components/Result/Modal.jsx
  FE/src/components/Result/ModalCost.jsx
  FE/src/config/ResultContextProvider.jsx
  FE/src/config/SearchBarContextProvider.jsx
Labels: FE
